# Generated by Django 3.1.5 on 2021-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(max_length=120, verbose_name='manager'),
        ),
    ]
