"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR =  os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@camfbcv@+!$dgq2c1-3jg#rrcs2i6rfnw)ofnweu*-ol2a710'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
<<<<<<< HEAD
    'django.contrib.staticfiles',

    'widget_tweaks', # 로그인 관련 앱
    'tinymce',
    'taggit.apps.TaggitAppConfig',
    'taggit_templatetags2',
    'assessment.apps.AssessmentConfig',
    'account',
    'board',
=======
    'django.contrib.staticfiles',    
    'widget_tweaks', # 로그인 관련 앱
    'assessment.apps.AssessmentConfig', # 추가
    # 'board',
    
    'account', #추가
    'tinymce',
    'blog',
    'instrouction',
  


>>>>>>> aa212d3adc88c7fa0181d078056f6adf725a276c
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
<<<<<<< HEAD
        'NAME': 'django_pro_db', # 데이터베이스 명
        'HOST': 'localhost', # 서버 IP
        'PORT': '3306', # 포트번호
        'USER': 'projectuser', # 사용자 ID
        'PASSWORD': '1234' # 비밀번호

=======
        'NAME': 'django_pro_db',  # 데이터베이스명
        'HOST': 'localhost',    # 서버 IP
        'PORT': '3306',         #포트 번호
<<<<<<< HEAD
        'USER': 'projectuser',      # 사용자 ID
        'PASSWORD': '1234'    # 비밀번호
=======
        'USER': 'root',      # 사용자 ID
        'PASSWORD': '123456'    # 비밀번호
>>>>>>> bfb980c6c8648df1016cc752bd3643599183ecca
    
>>>>>>> aa212d3adc88c7fa0181d078056f6adf725a276c
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_DIR = os.path.join(BASE_DIR, "static")

<<<<<<< HEAD
STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC_DIR,]
=======

# 로그인 관련 URL 디폴트 값
# LOGIN_URL = '/accounts/login/' # 로그인 페이지 URL
# LOGIN_REDIRECT_URL = '/accounts/profile' # 로그인 성공시 리다이렉트할 URL
# LOGOUT_REDIRECT_URL = '/' # 로그 아웃시 리다이렉트할 URL
LOGIN_REDIRECT_URL = '/' # 로그인 성공시 리다이렉트할 URL
>>>>>>> aa212d3adc88c7fa0181d078056f6adf725a276c
