# Generated by Django 3.1.5 on 2021-02-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DATE')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'assessment_posts',
                'ordering': ('-modify_dt',),
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'interface',
                'db_table': 'assessment_interface',
            },
        ),
    ]
