# Generated by Django 3.1.5 on 2021-02-05 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mix_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mix_project',
                'db_table': 'assessment_mix_project',
            },
        ),
        migrations.CreateModel(
            name='iot_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'iot_project',
                'db_table': 'assessment_iot_project',
            },
        ),
        migrations.CreateModel(
            name='Interface_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'interface_project',
                'db_table': 'assessment_interface_project',
            },
        ),
        migrations.CreateModel(
            name='gateway_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gateway_device',
                'db_table': 'assessment_gateway_device',
            },
        ),
        migrations.CreateModel(
            name='edge_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('performance_re', models.IntegerField(null=True)),
                ('writing', models.IntegerField(null=True)),
                ('writing_re', models.IntegerField(null=True)),
                ('attitude', models.IntegerField(null=True)),
                ('Portfolio', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edge_device',
                'db_table': 'assessment_edge_device',
            },
        ),
    ]
