# Generated by Django 3.1.5 on 2021-02-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='performance',
            field=models.IntegerField(null=True),
        ),
    ]
