# Generated by Django 3.1.5 on 2021-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20210202_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Portfolio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='attitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='performance_re',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='writing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='writing_re',
            field=models.IntegerField(null=True),
        ),
    ]
