# Generated by Django 3.1.6 on 2021-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readcount',
            field=models.IntegerField(blank=True, default=0, verbose_name='READCOUNT'),
        ),
    ]
